hex_game:
	g++ -std=c++11 -c exceptions.cpp
	g++ -std=c++11 -c cell.cpp
	g++ -std=c++11 -c abstract.cpp
	g++ -std=c++11 -c hvector.cpp
	g++ -std=c++11 -c array1d.cpp
	g++ -std=c++11 -c main.cpp
	g++ -std=c++11 -o game main.o cell.o abstract.o hvector.o array1d.o exceptions.o
	./game
	